### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by HLSiira** [samperlmutter/tkm#1]
The first build failed due to not having Cargo installed, and after installing cargo, the second build failed due to: 

error: Edition 2018 is unstable and only available for nightly builds of rustc. 
                                                                                
error: Could not compile `tui`.                                                 
warning: build failed, waiting for other jobs to finish...
error: failed to compile `tkm v0.1.0 (/home/liam/tkm)`, intermediate artifacts can be found at `/home/liam/tkm/target`

Caused by:
  build failed

**Comment by hunterkepley** [comment]
@HLSiira Make sure you have cargo and rust updated. If that doesn't work, install the _nightly_ version using rustup.

**Comment by samperlmutter** [comment]
You can set your toolchain to nightly by running `rustup default nightly`

**Comment by samperlmutter** [comment]
@HLSiira I clarified installation instructions in the README.
