### ISSUE TITLE
Build failed is this Linux only?

### ISSUE THREAD

**Issue by SenZmaKi** [samperlmutter/tkm#2]
Followed instructions still got build failed, I'm on windows, if it's Linux only at least add that in the README or about or something.

```
error[E0433]: failed to resolve: maybe a missing crate `sys`?
  --> C:\Users\PC\.cargo\registry\src\index.crates.io-6f17d22bba15001f\termion-1.5.6\src\lib.rs:24:9
   |
24 | pub use sys::size::terminal_size;
   |         ^^^ maybe a missing crate `sys`?
   |
   = help: consider adding `extern crate sys` to use the `sys` crate
```

**Comment by samperlmutter** [comment]
I think it supports everything except windows, but I will add that to the readme.

I am curious though. How did you find this project? I haven't updated it since I was in college.

**Comment by SenZmaKi** [comment]
I literally looked up task manager in terminal
